# Application
spring.application.name=skin-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-daf8e10n74is738r5er0-a.oregon-postgres.render.com:5432/skin_84v4
spring.datasource.username=admin
spring.datasource.password=HwJLIIxXTbuTgNyZSl73hEgzheT1w4or
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8080}

app.jwt.secret=MySuperSecretKeyForJwtAuthentication2026SecureKey12356773
app.jwt.expiration-ms=1000000

cors.allowed-origins=http://localhost:5173,https://skin-dev.onrender.com
app.upload.dir=/tmp/uploads