spring.application.name=opd-mini-module
server.port=${PORT:8080}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${jdbc:postgresql://dpg-d8g08kk2m8qs73efiuhg-a:5432/opd_db_iaht}
spring.datasource.username=${opd_db_iaht_user}
spring.datasource.password=${awRLy9d5pnPjIKIWt01DZodAsdYcnKwA}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true