# Application
spring.application.name=skin-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d9q5l4142hec739rir2g-a.oregon-postgres.render.com:5432/skin_yyu4
spring.datasource.username=admin
spring.datasource.password=IINhw20RjEgCxBDsAzQhWNT7nQ4Sqrhh
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8080}

app.jwt.secret=MySuperSecretKeyForJwtAuthentication2026SecureKey12356773
app.jwt.expiration-ms=1000000

cors.allowed-origins=http://localhost:5173,https://skin-dev.onrender.com
app.upload.dir=/tmp/uploads